kiev_tours/apps/landing_pages/urls.py
from django.conf.urls import url

from . import views

app_name = 'landing_pages'
urlpatterns = [
    # ex: /polls/
    url(r'^home/$', views.home, name='home'),
    #url(r'^$', views.IndexView.as_view()),
    # # ex: /polls/5/
    # # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # # ex: /polls/5/results/
    # # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

kiev_tours/apps/tours/urls.py
from django.conf.urls import url

from . import views

app_name = 'tours'
urlpatterns = [
    # ex: /polls/
    url(r'^tours/$', views.toursList, name='tours-list'),
    #url(r'^$', views.IndexView.as_view()),
    # # ex: /polls/5/
    url(r'^tours/(?P<tour_id>[0-9]+)/$', views.toursDetail, name='tours-detail'),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # # ex: /polls/5/results/
    # # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

kiev_tours/apps/wish_list/urls.py
from django.conf.urls import url

from . import views

app_name = 'wish_list'
# urlpatterns = [
#     # ex: /polls/
#     url(r'^tours/$', views.toursList, name='tours-list'),
#     #url(r'^$', views.IndexView.as_view()),
#     # # ex: /polls/5/
#     url(r'^tours/(?P<tour_id>[0-9]+)/$', views.toursDetail, name='tours-detail'),
#     # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
#     # # ex: /polls/5/results/
#     # # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#     # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
#     # # ex: /polls/5/vote/
#     # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]

kiev_tours/kiev_tours/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',
    	include('apps.landing_pages.urls', namespace="landing_pages")),
    url(r'',
    	include('apps.tours.urls', namespace="tours")),
]

kiev_tours/apps/landing_pages/models.py
from django.db import models
from apps.tours.models import Tour

# Create your models here.

kiev_tours/apps/tours/models.py
from django.db import models

class Tour(models.Model):

	# Const values.
	titleMaxLength = 200
	descriptionMaxLength = 4096

	tourWeekendDB = 0
	tourExcursionDB = 1
	tourPersonalGuideDB = 2

	tourWeekendUser = "Tour on weekend"
	tourExcursionUser = "Excursion tour"
	tourPersonalGuideUser = "Personal guide"

	tourChoices = (
		(tourWeekendDB, tourWeekendUser),
		(tourExcursionDB, tourExcursionUser),
		(tourPersonalGuideDB, tourPersonalGuideUser)
		)

# DB fields
	title = models.CharField(max_length = titleMaxLength)
	description = models.CharField(max_length = descriptionMaxLength)
	price = models.IntegerField(default = 0)
	rating = models.IntegerField(default = 0)
	visible = models.BooleanField(default = False)
	tourType = models.IntegerField(choices = tourChoices,
		default = tourExcursionDB)

	def __str__(self):
		return self.title

#TODO: Analyze the logic for main image(more than one, absent image, etc.)
	def getMainImage(self):
		tourImage = TourImage.objects.filter(tour_id=self.pk,
										mainImage=True,	visible = True).first()
		if tourImage != None:
			return tourImage.image
#TODO: Return path to some default picture
		return None

class TourImage(models.Model):
# DB fields
	tour = models.ForeignKey(Tour)
	# TODO: add some constraints to Image size.
	image = models.ImageField(upload_to='img/tours')
	visible = models.BooleanField(default = True)
	mainImage = models.BooleanField(default = False)

kiev_tours/apps/wish_list/models.py
from django.db import models

# Create your models here.

kiev_tours/apps/landing_pages/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader

# from django.core.urlresolvers import reverse
# from django.views.generic import TemplateView
# from django.views import generic
# from django.utils import timezone
# from PIL import Image

from .models import Tour

def home(request):
    tours = Tour.objects.all()
    template = loader.get_template('landing_pages/home.html')
    # context = {'aa' : "bb"}
    context = {
        'tours': tours,
    }
    return HttpResponse(template.render(context, request))

kiev_tours/apps/tours/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader

# from django.core.urlresolvers import reverse
# from django.views.generic import TemplateView
# from django.views import generic
# from django.utils import timezone
# from PIL import Image

from .models import Tour, TourImage

def toursList(request):
    tours = Tour.objects.all()
    template = loader.get_template('tours/tours-list.html')
    
    context = {}
    context['tours'] = []
    for tour in tours:
        context['tours'].append((tour,tour.getMainImage()))

    return HttpResponse(template.render(context, request))

def toursDetail(request, tour_id):
    tour = get_object_or_404(Tour, pk=tour_id)
    tourImgs = TourImage.objects.filter(tour_id=tour_id, visible=True)
    
    context = {
        'tour': tour,
    }
    context['imgs'] = []
    for tourImg in tourImgs:
        context['imgs'].append(tourImg.image)

    template = loader.get_template('tours/tour-details.html')

    return HttpResponse(template.render(context, request))

kiev_tours/apps/wish_list/views.py
from django.shortcuts import render

def view(request):
  response = HttpResponse( 'blah' )
  response.set_cookie( 'cookie_name', 'cookie_value' )
Retrieving a cookie:

def view(request):
  if request.COOKIES.has_key( 'cookie_name' ):
    value = request.COOKIES[ 'cookie_name' ]

# Create your views here.

kiev_tours/apps/landing_pages/templates/landing_pages/home.html
{% extends "base.html" %}

<!-- {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'testApp/style.css' %}" /> -->

<!-- <head>
	<title>KIEV TOURS</title>	
</head>

<body>

 -->
{% block content %}
	<a class="d-btn btn" href="{% url 'tours:tours-list' %}"><button>Tours</button></a>
{% endblock content %}

<!-- </body> -->

kiev_tours/apps/tours/templates/tours/tour-details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
{{ tour }}
{% for img in imgs %}
	<img src="{% static img %}">
{% endfor %}

{% endblock content %}

kiev_tours/apps/tours/templates/tours/tours-list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extrastyles %}
	<link rel="stylesheet" type="text/css" href="{% static 'tours/css/tours-list.css' %}" />
{% endblock extrastyles %}

{% block content %}

<div class="clearfix tours-list-wrapper">
	
	<div class="about-tours clearfix">
		<div class="tours-list-overlay vertical">
			<h3>WELCOME TO KIEV!</h3>
			<p>See below the places we advice you to visit.</p>
		</div>
	</div>

	<div class="services-descr">
		<h3>With KIEV-TOURS your can ... Choose the comfortable service:</h3>
	</div>

	<div class="panel-group excursions" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse1">Excursions - is the most popular service. You just choose the places you want to visit and our guides will do the best you to love visiting Kiev!</br>
				Look what we've prepared for you:
				</h4>
			</div>
			<div id="collapse1" class="panel-collapse collapse text-left">
				{% for tour, tourImage in tours %}
				<a href="{% url 'tours:tours-detail' tour.id %}">
					<div class="one-tour-info col-lg-4 col-sm-6">
						<img class="main-tour-img vertical" src="{% static tourImage %}">
					</div>
				</a>
				{% endfor %}
			</div>
		</div>
	</div>

	<div class="tours-weekend">
		
	</div>

	<div class="guide">
		
	</div>

</div>

{% endblock content %}

kiev_tours/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		{% block styles %}    
		<!-- Bootstrap -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/base.css' %}" rel="stylesheet">
		{% endblock styles %}
		{% block extrastyles %}{% endblock extrastyles %}
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'landing_pages:home' %}">Home page</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'tours:tours-list' %}">Tours<span class="sr-only">(current)</span></a></li>
						<li><a href="#">Link</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">Separated link</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">One more separated link</a></li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Search">
						</div>
						<button type="submit" class="btn btn-default">Submit</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">Link</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
		{% block content %}{% endblock content %}

		{% block bottom-scripts %}
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
		{% endblock bottom-scripts %}
		{% block extra-bottom-scripts %}{% endblock extra-bottom-scripts %}
	</body>
</html>